- the-blue-alliance-ios/EventViewController.m
> Only show District Point option on district events.

- the-blue-alliance-ios/Base.lproj/Main.storyboard
- the-blue-alliance-ios/Models/Match.m
- the-blue-alliance-ios/TBAMatchTableViewCell.m
I *believe* we get the same functionality of showing the times in the user's timezone for free like TBA does on the web (to test this, check out Dallas in 2015 - there's some matches without times)
It's not super pretty, but these Match cells aren't super pretty. Might need to look in to a new layout for them...
> Adds time to match cells

- the-blue-alliance-ios/AppDelegate.m
Removes that dumb 1px white shadow on the navigation bar
> Removes shadow from navigation bar

- the-blue-alliance-ios/Base.lproj/Main.storyboard
In an attempt to MVP this app out let's just nuke Settings and MyTBA and not worry about developing them for now.
Of course we'll revisit this and add it to the app, but for now let's focus on delivering something.
> Nuke Settings and MyTBA

- the-blue-alliance-ios/Base Classes/TBAEventsViewController.m
- the-blue-alliance-ios/EventTeamStat.h
- the-blue-alliance-ios/EventTeamStat.m
- the-blue-alliance-ios/EventTeamViewController.m
- the-blue-alliance-ios/EventsStoryboard.storyboard
- the-blue-alliance-ios/Models/Event.h
- the-blue-alliance-ios/Models/Event.m
- the-blue-alliance-ios/Models/Team.h
- the-blue-alliance-ios/Models/Team.m
- the-blue-alliance-ios/TBA.xcdatamodeld/The Blue Alliance.xcdatamodel/contents
- the-blue-alliance-ios/TBAAlliancesViewController.m
- the-blue-alliance-ios/TBAAwardsViewController.m
- the-blue-alliance-ios/TBADistrictRankingBreakdownViewController.m
- the-blue-alliance-ios/TBADistrictsViewController.m
- the-blue-alliance-ios/TBAEventRankingsViewController.m
- the-blue-alliance-ios/TBAMatchViewController.m
- the-blue-alliance-ios/TBAMatchesViewController.m
- the-blue-alliance-ios/TBAMediaCollectionViewController.m
- the-blue-alliance-ios/TBAPointsViewController.m
- the-blue-alliance-ios/TBATeamAtDistrictSummaryViewController.m
- the-blue-alliance-ios/TBATeamAtEventStatsViewController.h
- the-blue-alliance-ios/TBATeamAtEventStatsViewController.m
- the-blue-alliance-ios/TBATeamsViewController.m
- the-blue-alliance.xcodeproj/project.pbxproj
A little out of scope - also removed "unnecessary" (I think we don't need them, or at least we shouldn't be calling them so I'll fix it if it doesn't already remove them) hideNoDataView calls from refresh methods
> [Closes #36] Add team at event stats

- Podfile
- Podfile.lock
- the-blue-alliance-ios/EventStatsViewController.m
- the-blue-alliance-ios/EventViewController.m
- the-blue-alliance-ios/EventsStoryboard.storyboard
- the-blue-alliance-ios/Models/Event.h
- the-blue-alliance-ios/Models/Event.m
- the-blue-alliance-ios/Models/Team.m
- the-blue-alliance-ios/TBA.xcdatamodeld/The Blue Alliance.xcdatamodel/contents
- the-blue-alliance-ios/TBAEventStatsViewController.h
- the-blue-alliance-ios/TBAEventStatsViewController.m
- the-blue-alliance-ios/TBAInfoViewController.m
- the-blue-alliance-ios/TBATeamStatsTableViewCell.h
- the-blue-alliance-ios/TBATeamStatsTableViewCell.m
- the-blue-alliance-ios/TBATeamStatsViewController.h
- the-blue-alliance-ios/TBATeamStatsViewController.m
- the-blue-alliance-ios/TBATeamTableViewCell.m
- the-blue-alliance.xcodeproj/project.pbxproj
Had to pull in that OrderedDictionary library again for setting up the event stats data properly. I might take a pass at writing it with generics so we can get some type safety back... but not immediately.
> [Closes #37] Adds event stats view

- the-blue-alliance-ios/EventsStoryboard.storyboard
- the-blue-alliance-ios/Models/Team.h
- the-blue-alliance-ios/Models/Team.m
- the-blue-alliance-ios/TBAAllianceCell.h
- the-blue-alliance-ios/TBAAllianceCell.m
- the-blue-alliance-ios/TBAAlliancesViewController.h
- the-blue-alliance-ios/TBAAlliancesViewController.m
Didn't switch the team number to UIButton because it would've turned into kind of mess with autolayout.
Closes #58
> Tap teams in alliance view to go to Team@Event.

- Podfile
- the-blue-alliance-ios.xcworkspace/xcshareddata/the-blue-alliance-ios.xcscmblueprint
- the-blue-alliance-ios/AppDelegate.swift
- the-blue-alliance-ios/Base.lproj/Main.storyboard
- the-blue-alliance-ios/View Controllers/Events/EventInfoTableViewController.swift
- the-blue-alliance-ios/View Controllers/Events/EventViewController.swift
- the-blue-alliance-ios/View Controllers/Events/EventsStoryboard.storyboard
- the-blue-alliance-ios/View Controllers/Events/EventsTableViewController.swift
Just need to fix the issue where I've got a button on that master navigation controller... has to do with L107 in AppDelegate
> Almost got the split view controller setup properly

- the-blue-alliance-ios/Core Data/Match.swift
- the-blue-alliance-ios/Core Data/TBA.xcdatamodeld/TBA.xcdatamodel/contents
Fixes #94 - a little out of scope but also changing redBreakdown/blueBreakdown to be typed in Core Data instead of the file
> Only set Core Data score if score > -1

- the-blue-alliance-ios/Core Data/EventAlliance.swift
- the-blue-alliance-ios/Core Data/Webcast.swift
My TBAKit bump bork'd something...
> Fix swift branch

- the-blue-alliance-ios.xcodeproj/project.pbxproj
- the-blue-alliance-ios/View Controllers/Districts/DistrictsStoryboard.storyboard
- the-blue-alliance-ios/View Controllers/Districts/Team@District/DistrictTeamSummaryTableViewController.swift
- the-blue-alliance-ios/View Controllers/Districts/Team@District/TeamAtDistrictViewController.swift
> Team@District Summary VC

- Podfile
- Podfile.lock
- tba-unit-tests/Date_TBA_Tests.swift
- tba-unit-tests/Int16_Suffix_Tests.swift
- the-blue-alliance-ios.xcodeproj/project.pbxproj
- the-blue-alliance-ios.xcodeproj/xcshareddata/xcschemes/The Blue Alliance.xcscheme
- the-blue-alliance-ios/AppDelegate.swift
- the-blue-alliance-ios/Frameworks/MyTBAKit/Models/MyTBAFavorite.swift
- the-blue-alliance-ios/Frameworks/MyTBAKit/Models/MyTBAModel.swift
- the-blue-alliance-ios/Frameworks/MyTBAKit/Models/MyTBARegister.swift
- the-blue-alliance-ios/Frameworks/MyTBAKit/Models/MyTBASubscription.swift
- the-blue-alliance-ios/Frameworks/MyTBAKit/MyTBA.swift
- the-blue-alliance-ios/Protocols/Refreshable.swift
- the-blue-alliance-ios/Services/PushService.swift
- the-blue-alliance-ios/Settings.bundle/Acknowledgements.plist
- the-blue-alliance-ios/View Controllers/Base/Data Controllers/TBACollectionViewController.swift
- the-blue-alliance-ios/View Controllers/Base/Data Controllers/TBATableViewController.swift
- the-blue-alliance-ios/View Controllers/Base/Data Controllers/TBAViewController.swift
- the-blue-alliance-ios/View Controllers/MyTBA/MyTBAStoryboard.storyboard
- the-blue-alliance-ios/View Controllers/MyTBA/MyTBATableViewController.swift
- the-blue-alliance-ios/View Controllers/MyTBA/MyTBAViewController.swift
> Use Firebase Auth for myTBA

- tba-unit-tests/Extensions/RemoteConfig+TBA_Tests.swift
- the-blue-alliance-ios/AppDelegate.swift
- the-blue-alliance-ios/Extensions/RemoteConfig+TBA.swift
- the-blue-alliance-ios/RemoteConfigDefaults.plist
The myTBA server stuff is super rough, and is eating up so much of my time. Going to hide this behind a feature flag.
> Hide myTBA behind feature flag

- Podfile
- Podfile.lock
- subtrees/the-blue-alliance-react/package-lock.json
- subtrees/the-blue-alliance-react/package.json
- the-blue-alliance-ios.xcodeproj/project.pbxproj
- the-blue-alliance-ios/Services/ReactNativeService.swift
- the-blue-alliance-ios/Settings.bundle/Acknowledgements.plist
That ReactNativeService sure does need some tests
> Update to new the-blue-alliance-react, fix ReactNativeService to correctly identify downloaded bundle

- the-blue-alliance-ios/View Controllers/Districts/DistrictsStoryboard.storyboard
- the-blue-alliance-ios/View Controllers/Events/EventsStoryboard.storyboard
- the-blue-alliance-ios/View Controllers/MyTBA/MyTBAStoryboard.storyboard
- the-blue-alliance-ios/View Controllers/Teams/TeamsStoryboard.storyboard
No more white space down by the home bar on the X
> Fix storyboards to use safe area layout guides properly

- .gitignore
- .travis.yml
- Gemfile
- Gemfile.lock
- README.md
- bin/secrets.rb
- bin/setup_ejson.sh
- ejson/secrets.ejson
- tba-unit-tests/Services/Secrets_Tests.swift
- tba-unit-tests/TestSecrets.plist
- the-blue-alliance-ios.xcodeproj/project.pbxproj
- the-blue-alliance-ios/AppDelegate.swift
- the-blue-alliance-ios/Secrets.plist
- the-blue-alliance-ios/Services/Secrets.swift
This one is mostly to make sure Travis builds properly on CI with our new secrets setup stuff
> Load TBA API key from secrets

- tba-unit-tests/Services/ReactNativeService_Tests.swift
- tba-unit-tests/TBATestCase.swift
- tba-unit-tests/View Controllers/Settings/SettingsViewController_Tests.swift
- the-blue-alliance-ios.xcodeproj/project.pbxproj
- the-blue-alliance-ios/App Delegate/AppDelegate.swift
- the-blue-alliance-ios/Protocols/Observable.swift
- the-blue-alliance-ios/Services/ReactNativeService.swift
- the-blue-alliance-ios/View Controllers/Districts/Team@District/DistrictBreakdownViewController.swift
- the-blue-alliance-ios/View Controllers/Events/EventInfoViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Match/MatchBreakdownViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Match/MatchInfoViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Stats/EventStatsViewController.swift
- the-blue-alliance-ios/View Controllers/Settings/SettingsViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/TeamStatsViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/TeamSummaryViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/TeamViewController.swift
- Adds ReactNativeMetadata to supply/observe React Native metadata
- Fix broken SettingsViewController tests
- Removes `observerPredicate
> Add ReactNativeMetadata

- the-blue-alliance-ios/Core Data/Award.swift
- the-blue-alliance-ios/Core Data/DistrictEventPoints.swift
- the-blue-alliance-ios/Core Data/DistrictRanking.swift
- the-blue-alliance-ios/Core Data/EventAlliance.swift
- the-blue-alliance-ios/Core Data/EventRanking.swift
- the-blue-alliance-ios/Core Data/EventTeamStat.swift
- the-blue-alliance-ios/Core Data/Media.swift
- the-blue-alliance-ios/View Controllers/Districts/DistrictEventsViewController.swift
- the-blue-alliance-ios/View Controllers/Districts/DistrictRankingsViewController.swift
- the-blue-alliance-ios/View Controllers/Districts/Team@District/DistrictBreakdownViewController.swift
- the-blue-alliance-ios/View Controllers/Districts/Team@District/DistrictTeamSummaryViewController.swift
- the-blue-alliance-ios/View Controllers/Events/EventAlliancesViewController.swift
- the-blue-alliance-ios/View Controllers/Events/EventAwardsViewController.swift
- the-blue-alliance-ios/View Controllers/Events/EventDistrictPointsViewController.swift
- the-blue-alliance-ios/View Controllers/Events/EventRankingsViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Match/MatchesViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Stats/EventTeamStatsViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/TeamMediaCollectionViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/TeamStatsViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/TeamSummaryViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/TeamsViewController.swift
Reverts the-blue-alliance/the-blue-alliance-ios#253
> Revert "Fix model relationships being overwritten by empty cache responses"

- the-blue-alliance-ios/Operations/App Setup/PersistentContainerOperation.swift
Fixes #258 - I don't particularly love this solution, but I've seen these merge errors happen a few places in the app. Short of auditing this kinda weird edge case, we'll just set a merge policy and hope it's right 🙏
> Set merge policy for managed object context

- Podfile
- Podfile.lock
- the-blue-alliance-ios.xcodeproj/project.pbxproj
- the-blue-alliance-ios/Info.plist
- the-blue-alliance-ios/Settings.bundle/Acknowledgements.plist
- the-blue-alliance-ios/View Controllers/Teams/TeamMediaCollectionViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/TeamViewController.swift
> Show team media inside app, support peek/pop for team media

- fastlane/Fastfile
> Disable UI tests

- tba-unit-tests/Core Data/Event/EventTests.swift
- tba-unit-tests/Core Data/Team/TeamKeyTests.swift
- the-blue-alliance-ios/Core Data/Event/Event.swift
- the-blue-alliance-ios/Info.plist
- the-blue-alliance-ios/View Controllers/Districts/DistrictEventsViewController.swift
- the-blue-alliance-ios/View Controllers/Districts/DistrictRankingsViewController.swift
- the-blue-alliance-ios/View Controllers/Districts/DistrictsViewController.swift
- the-blue-alliance-ios/View Controllers/Districts/Team@District/DistrictBreakdownViewController.swift
- the-blue-alliance-ios/View Controllers/Districts/Team@District/DistrictTeamSummaryViewController.swift
- the-blue-alliance-ios/View Controllers/Events/EventAlliancesViewController.swift
- the-blue-alliance-ios/View Controllers/Events/EventAwardsViewController.swift
- the-blue-alliance-ios/View Controllers/Events/EventDistrictPointsViewController.swift
- the-blue-alliance-ios/View Controllers/Events/EventInfoViewController.swift
- the-blue-alliance-ios/View Controllers/Events/EventRankingsViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Match/MatchBreakdownViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Match/MatchInfoViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Match/MatchesViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Stats/EventStatsViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Stats/EventTeamStatsViewController.swift
- the-blue-alliance-ios/View Controllers/Events/WeekEventsViewController.swift
- the-blue-alliance-ios/View Controllers/Events/YearSelectViewController.swift
- the-blue-alliance-ios/View Controllers/MyTBA/MyTBATableViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/TeamEventsViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/TeamInfoViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/TeamMediaCollectionViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/TeamStatsViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/TeamSummaryViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/TeamViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/TeamsViewController.swift
- the-blue-alliance-ios/View Elements/Events/EventAllianceCellViewModel.swift
Fix Event Awards overwrite when viewing Team Status, fix District Points crash, set merge policy for background contexts, fix alliance picks not showing, disable refreshing in Years
> Fix b7 bugs

- tba-unit-tests/Core Data/Event/EventTests.swift
- tba-unit-tests/Core Data/Match/MatchTests.swift
- tba-unit-tests/Core Data/Team/TeamTests.swift
- the-blue-alliance-ios.xcodeproj/project.pbxproj
- the-blue-alliance-ios/Core Data/Event/Event.swift
- the-blue-alliance-ios/Core Data/Match/Match.swift
- the-blue-alliance-ios/Core Data/Team/Team.swift
- the-blue-alliance-ios/Frameworks/MyTBAKit/Protocols/MyTBASubscribable.swift
Trying to pull changes from #286 to make it more manageable
> Adds MyTBASubscribable

- README.md
- fastlane/Appfile
- the-blue-alliance-ios.xcodeproj/project.pbxproj
Working our way towards prod, we can finally set these now 🤗
> Change bundle identifier and team

- tba-unit-tests/Core Data/myTBA/FavoriteTests.swift
- tba-unit-tests/Core Data/myTBA/MyTBAEntityTests.swift
- tba-unit-tests/Core Data/myTBA/SubscriptionTests.swift
- the-blue-alliance-ios.xcodeproj/project.pbxproj
- the-blue-alliance-ios/Core Data/MyTBA/Favorite.swift
- the-blue-alliance-ios/Core Data/MyTBA/MyTBAEntity.swift
- the-blue-alliance-ios/Core Data/MyTBA/Subscription.swift
- the-blue-alliance-ios/Core Data/TBA.xcdatamodeld/TBA.xcdatamodel/contents
- the-blue-alliance-ios/Frameworks/MyTBAKit/Models/MyTBAModel.swift
- the-blue-alliance-ios/View Controllers/MyTBA/MyTBATableViewController.swift
- the-blue-alliance-ios/View Controllers/MyTBA/MyTBAViewController.swift
Part of landing smaller changes in #286
> Modifies Favorite/Subscription/MyTBAEntity to be a little bit nicer

- tba-unit-tests/Frameworks/MyTBAKit/MyTBATests.swift
- tba-unit-tests/Operations/myTBA/MyTBASignOutOperation_Tests.swift
- the-blue-alliance-ios.xcodeproj/project.pbxproj
- the-blue-alliance-ios/Frameworks/MyTBAKit/Models/MyTBARegister.swift
- the-blue-alliance-ios/Frameworks/MyTBAKit/MyTBA.swift
Part of cutting code out of #286 to make it smaller
> Pass UUID to MyTBA

- the-blue-alliance-ios/Frameworks/MyTBAKit/Models/MyTBAFavorite.swift
- the-blue-alliance-ios/Frameworks/MyTBAKit/Models/MyTBAPreferences.swift
- the-blue-alliance-ios/Frameworks/MyTBAKit/Models/MyTBARegister.swift
- the-blue-alliance-ios/Frameworks/MyTBAKit/Models/MyTBASubscription.swift
Removing some code out of #286 - consumes updates from https://github.com/the-blue-alliance/the-blue-alliance/pull/2305 and closes #173
> Add MyTBA Preferences, update MyTBA models

- fastlane/Gymfile
> Quiet down build output when running fastlane

- Brewfile
- README.md
- fastlane/Fastfile
- fastlane/README.md
> Adds tooling to easily install project dependencies

- tba-unit-tests/Frameworks/MyTBAKit/Models/MyTBAFavoriteTests.swift
- tba-unit-tests/Frameworks/MyTBAKit/Models/MyTBAPreferencesTests.swift
- tba-unit-tests/Frameworks/MyTBAKit/Models/MyTBARegisterTests.swift
- tba-unit-tests/Frameworks/MyTBAKit/Models/MyTBASubscriptionTests.swift
- tba-unit-tests/Frameworks/MyTBAKit/MyTBATests.swift
- tba-unit-tests/Frameworks/MyTBAKit/Testing/MockMyTBA.swift
- tba-unit-tests/Frameworks/MyTBAKit/Testing/MyTBATestCase.swift
- tba-unit-tests/Frameworks/MyTBAKit/data/favorites_list.json
- tba-unit-tests/Frameworks/MyTBAKit/data/model_setPreferences.json
- tba-unit-tests/Frameworks/MyTBAKit/data/model_setPreferences_401.json
- tba-unit-tests/Frameworks/MyTBAKit/data/register.json
- tba-unit-tests/Frameworks/MyTBAKit/data/register_401.json
- tba-unit-tests/Frameworks/MyTBAKit/data/subscriptions_list.json
- tba-unit-tests/Frameworks/MyTBAKit/data/unregister.json
- tba-unit-tests/Frameworks/MyTBAKit/data/unregister_401.json
- tba-unit-tests/Operations/myTBA/MyTBASignOutOperation_Tests.swift
- the-blue-alliance-ios.xcodeproj/project.pbxproj
- the-blue-alliance-ios/Frameworks/MyTBAKit/Models/MyTBAPreferences.swift
- the-blue-alliance-ios/Frameworks/MyTBAKit/Models/MyTBARegister.swift
- the-blue-alliance-ios/Frameworks/MyTBAKit/MyTBA.swift
- the-blue-alliance-ios/Operations/myTBA/MyTBASignOutOperation.swift
Adding tests for the MyTBA code (mostly so we can have a MockMyTBA that has fake requests) - starting with the MyTBA test coverage
> Add MyTBA.swift tests

- fastlane/Fastfile
Everything I'm reading makes it seem like Travis shouldn't timeout our build - I'm not sure what happened last time, but we're going to try again
> Wait for beta builds on CI

- the-blue-alliance-ios/App Delegate/AppDelegate.swift
> Add MyTBA VC to root tab bar

- the-blue-alliance-ios/App Delegate/AppDelegate.swift
- the-blue-alliance-ios/Protocols/Alertable.swift
- the-blue-alliance-ios/Protocols/Refreshable.swift
- the-blue-alliance-ios/View Controllers/Districts/District/DistrictEventsViewController.swift
- the-blue-alliance-ios/View Controllers/Districts/District/DistrictRankingsViewController.swift
- the-blue-alliance-ios/View Controllers/Districts/District/Team@District/DistrictBreakdownViewController.swift
- the-blue-alliance-ios/View Controllers/Districts/District/Team@District/DistrictTeamSummaryViewController.swift
- the-blue-alliance-ios/View Controllers/Districts/DistrictsViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Event/EventAlliancesViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Event/EventAwardsViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Event/EventDistrictPointsViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Event/EventInfoViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Event/EventRankingsViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Event/Stats/EventStatsViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Event/Stats/EventTeamStatsViewController.swift
- the-blue-alliance-ios/View Controllers/Events/WeekEventsViewController.swift
- the-blue-alliance-ios/View Controllers/Events/YearSelectViewController.swift
- the-blue-alliance-ios/View Controllers/Match/MatchBreakdownViewController.swift
- the-blue-alliance-ios/View Controllers/Match/MatchInfoViewController.swift
- the-blue-alliance-ios/View Controllers/Match/MatchesViewController.swift
- the-blue-alliance-ios/View Controllers/MyTBA/MyTBATableViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/Team/Team@Event/TeamStatsViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/Team/Team@Event/TeamSummaryViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/Team/TeamEventsViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/Team/TeamInfoViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/Team/TeamMediaCollectionViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/Team/TeamViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/TeamsViewController.swift
Closes #196, #258, #307, #326, and hopefully people will stop emailing me
> Convert view controllers to using new background insert methods, remove noisy alerts

- Podfile.lock
- tba-unit-tests/Frameworks/MyTBAKit/Models/MyTBARegisterTests.swift
- tba-unit-tests/Frameworks/MyTBAKit/MyTBATests.swift
- the-blue-alliance-ios.xcodeproj/project.pbxproj
- the-blue-alliance-ios/App Delegate/AppDelegate.swift
- the-blue-alliance-ios/Frameworks/MyTBAKit/Models/MyTBAModel.swift
- the-blue-alliance-ios/Frameworks/MyTBAKit/Models/MyTBAPing.swift
- the-blue-alliance-ios/Frameworks/MyTBAKit/Models/MyTBAPreferences.swift
- the-blue-alliance-ios/Frameworks/MyTBAKit/Models/MyTBARegister.swift
- the-blue-alliance-ios/Frameworks/MyTBAKit/MyTBA.swift
- the-blue-alliance-ios/Operations/myTBA/MyTBASignOutOperation.swift
- the-blue-alliance-ios/Services/PushService.swift
- the-blue-alliance-ios/View Controllers/Settings/Notifications/NotificationsViewController.swift
- the-blue-alliance-ios/View Controllers/Settings/SettingsViewController.swift
- the-blue-alliance-ios/View Elements/Settings/NotificationStatusTableViewCell.xib
Also bumps Fabric/Crashlytics because we've been having a problem with dSYM upoads
> Finish implementation of notification troubleshooting view controller

- tba-unit-tests/TBATestCase.swift
- tba-unit-tests/View Controllers/myTBA/MyTBATableViewControllerTests.swift
- the-blue-alliance-ios/App Delegate/AppDelegate.swift
- the-blue-alliance-ios/Core Data/MyTBA/MyTBAEntity.swift
- the-blue-alliance-ios/Frameworks/MyTBAKit/Models/MyTBAModel.swift
- the-blue-alliance-ios/Frameworks/MyTBAKit/Models/MyTBAPreferences.swift
- the-blue-alliance-ios/Services/PushService.swift
- the-blue-alliance-ios/View Controllers/MyTBA/MyTBATableViewController.swift
- the-blue-alliance-ios/View Controllers/MyTBA/MyTBAViewController.swift
> Register myTBA after Google sign in, fix myTBA Team@Event crash

- fastlane/Fastfile
> Upload symbols to Crashlytics during beta

- the-blue-alliance-ios/View Controllers/Match/MatchInfoViewController.swift
Closes #272 - also, our auto layout constraints should stop breaking in this view, finally
> Fix match info view not respecting safe area

- the-blue-alliance-ios/View Controllers/Events/YearSelectViewController.swift
> Adds Done button to week select

- tba-unit-tests/Core Data/Match/MatchTests.swift
- the-blue-alliance-ios/Core Data/CoreDataContextObserver.swift
- the-blue-alliance-ios/Core Data/Event/Event.swift
- the-blue-alliance-ios/Core Data/Match/Match.swift
- the-blue-alliance-ios/Services/StatusService.swift
- the-blue-alliance-ios/View Controllers/Teams/Team/Team@Event/TeamSummaryViewController.swift
- the-blue-alliance-ios/View Elements/Base/LoadingTableViewCell.swift
- the-blue-alliance-ios/View Elements/Base/ReverseSubtitleTableViewCell.swift
> TeamSummaryViewController fixes

- the-blue-alliance-ios/View Controllers/Events/Event/EventInfoViewController.swift
- the-blue-alliance-ios/View Controllers/Settings/SettingsViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/Team/TeamInfoViewController.swift
> Remove max enum cases for CaseIterable

- the-blue-alliance-ios.xcodeproj/project.pbxproj
- the-blue-alliance-ios/App Delegate/AppDelegate.swift
- the-blue-alliance-ios/Info.plist
> Adds methods/capability for remote notifications

- the-blue-alliance-ios/Services/ReactNativeService.swift
For https://github.com/the-blue-alliance/the-blue-alliance-react/pull/7
> Change name of React Native zip

- the-blue-alliance-ios/Operations/App Setup/AppSetupOperation.swift
> Fixes status service fetching/saving before persistent container is setup

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
> Added issue and PR template

- the-blue-alliance-ios/App Delegate/AppDelegate.swift
> Fix double register call

- tba-unit-tests/Core Data/Team/TeamMediaTests.swift
- tba-unit-tests/Frameworks/TBAKit/data/team_frc2337_media_2017.json
- the-blue-alliance-ios/Core Data/TBA.xcdatamodeld/TBA.xcdatamodel/contents
- the-blue-alliance-ios/Core Data/Team/TeamMedia.swift
- the-blue-alliance-ios/Frameworks/TBAKit/Sources/TBATeam.swift
- the-blue-alliance-ios/View Controllers/Teams/Team/TeamMediaCollectionViewController.swift
Consumes changes in https://github.com/the-blue-alliance/the-blue-alliance/pull/2368
> Load team media from URLs from API URL strings

- tba-unit-tests/Core Data/Match/MatchTests.swift
- the-blue-alliance-ios/Core Data/Match/Match.swift
- the-blue-alliance-ios/View Elements/Match/MatchSummaryView.swift
While reviewing some other code, I finally figured out why we had to reverse match teams to get them to show up properly. This fixes that, so we don't do any reverse magic
> Fix having to reverse alliance teams

- tba-unit-tests/Core Data/Match/MatchAllianceTests.swift
- the-blue-alliance-ios/Core Data/TBA.xcdatamodeld/TBA.xcdatamodel/contents
Core Data saves are failing right now, since they're non-optional
> Make match score optional

- tba-unit-tests/Core Data/CoreDataTestCase.swift
- tba-unit-tests/Core Data/Team/TeamTests.swift
- the-blue-alliance-ios/Core Data/TBA.xcdatamodeld/TBA.xcdatamodel/contents
- the-blue-alliance-ios/Core Data/Team/Team.swift
- the-blue-alliance-ios/Frameworks/TBAKit/Sources/TBATeam.swift
Follow up change for #425 - closes #426
> Remove motto from Team Core Data models

- tba-unit-tests/Core Data/Team/TeamKeyTests.swift
- tba-unit-tests/Core Data/Team/TeamTests.swift
- tba-unit-tests/Extensions/UIBarButtonItem+TBATests.swift
- tba-unit-tests/Extensions/UIImage+TBATests.swift
- the-blue-alliance-ios.xcodeproj/project.pbxproj
- the-blue-alliance-ios/Core Data/Team/Team.swift
- the-blue-alliance-ios/Core Data/Team/TeamKey.swift
- the-blue-alliance-ios/Extensions/ContainerViewController+Team.swift
- the-blue-alliance-ios/Extensions/UIBarButtonItem+TBA.swift
- the-blue-alliance-ios/Extensions/UIImage+TBA.swift
- the-blue-alliance-ios/View Controllers/Districts/District/DistrictViewController.swift
- the-blue-alliance-ios/View Controllers/Districts/District/Team@District/TeamAtDistrictViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Event/EventAlliancesViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Event/EventAwardsViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Event/EventDistrictPointsViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Event/EventViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Event/Stats/EventStatsContainerViewController.swift
- the-blue-alliance-ios/View Controllers/Events/EventsContainerViewController.swift
- the-blue-alliance-ios/View Controllers/MyTBA/MyTBAPreferenceViewController.swift
- the-blue-alliance-ios/View Controllers/MyTBA/MyTBAViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/Team/Team@Event/TeamAtEventViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/Team/TeamViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/TeamsContainerViewController.swift
> Push to Team/Event from Team@Event and Team@District

- tba-unit-tests/Core Data/Match/MatchTests.swift
- the-blue-alliance-ios/Core Data/Match/Match.swift
- the-blue-alliance-ios/View Controllers/Match/MatchInfoViewController.swift
- the-blue-alliance-ios/View Elements/Match/MatchViewModel.swift
> Use predicted time for upcoming matches, fallback to scheduled time

- tba-unit-tests/Core Data/Protocols/SurfableTests.swift
- the-blue-alliance-ios.xcodeproj/project.pbxproj
- the-blue-alliance-ios/Core Data/Event/Event.swift
- the-blue-alliance-ios/Core Data/Protocols/Surfable.swift
- the-blue-alliance-ios/Core Data/Team/Team.swift
- the-blue-alliance-ios/View Controllers/Events/Event/EventInfoViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/Team/TeamInfoViewController.swift
Fixes #460 
This also really needs snapshot tests, but we've yet to make that it's own target and I don't want to have to move tests ugh.
> Fix website row showing up in Team/Event info for models without websites

- the-blue-alliance-ios/View Controllers/Teams/TeamsViewController.swift
> Add city search to Teams filter

- tba-unit-tests/Frameworks/MyTBAKit/Testing/MockMyTBA.swift
- the-blue-alliance-ios/Frameworks/MyTBAKit/MyTBA.swift
> Point myTBA to new client API service

- the-blue-alliance-ios/View Controllers/Match/MatchInfoViewController.swift
- the-blue-alliance-ios/View Elements/Awards/AwardTableViewCell.swift
- the-blue-alliance-ios/View Elements/Events/EventAllianceTableViewCell.swift
- the-blue-alliance-ios/View Elements/Info/InfoTableViewCell.swift
- the-blue-alliance-ios/View Elements/Match/MatchSummaryView.swift
- the-blue-alliance-ios/View Elements/Match/MatchViewModel.swift
> Fix Match Info not showing team numbers, add RP to 2019 Match cells, add removeArrangedSubview to all stackView removals

- Podfile
- Podfile.lock
- the-blue-alliance-ios/Settings.bundle/Acknowledgements.plist
> Add Firebase Performance for network response time monitoring

- the-blue-alliance-ios/Services/StatusService.swift
Ran in to this one (which is currently our biggest crash) - I don't know exactly what's causing it, but this should fix it.
> Fix unwrap crash for setupStatusObservers for StatusService

- the-blue-alliance-ios/Services/PushService.swift
This is going to be important for notifications
> Register push token on sign in

- tba-unit-tests/Extensions/Date+TBA_Tests.swift
- the-blue-alliance-ios/Extensions/Date+TBA.swift
- the-blue-alliance-ios/View Controllers/Events/WeekEventsViewController.swift
> Fix early week switching

- the-blue-alliance-ios/View Controllers/Base/Containers/ContainerViewController.swift
This was a suggestion - I figure we can try it out and see how we like it
> Stop hiding nav bar when pushing to a new view controller

- Podfile
- Podfile.lock
- the-blue-alliance-ios.xcodeproj/project.pbxproj
- the-blue-alliance-ios/Info.plist
- the-blue-alliance-ios/Settings.bundle/Acknowledgements.plist
- the-blue-alliance-ios/View Elements/Media/PlayerView.swift
I'm 🙏 this fixes our WK crashes. Closes #503 #328 #231 
Tested on iOS 12/11, on iPad/iPhone
> Replace YouTube library with XCDYouTubeKit/AVKit

- .travis.yml
- Gemfile
Closes https://github.com/the-blue-alliance/the-blue-alliance-ios/issues/552
> Remove Cocoapods check

- Frameworks/MyTBAKit/Testing/MockMyTBA.swift
- Frameworks/MyTBAKit/Tests/MyTBATestCase.swift
- Frameworks/TBAKit/Testing/MockTBAKit.swift
- Frameworks/TBAKit/Tests/TBAKitTestCase.swift
- tba-unit-tests/TBATestCase.swift
Closes https://github.com/the-blue-alliance/the-blue-alliance-ios/issues/553
> DRY mock bundles for TBAKit and MyTBAKit

- the-blue-alliance-ios/View Elements/Media/PlayerView.swift
I think this will work? I'm unclear about the memory management for `NSKeyValueObservation`, but things aren't crashing and the memory graph looks good. Closes https://github.com/the-blue-alliance/the-blue-alliance-ios/issues/551
> Use KVO to show Match video player controls

- the-blue-alliance-ios/View Controllers/Districts/District/Team@District/DistrictBreakdownViewController.swift
- the-blue-alliance-ios/View Controllers/Districts/District/Team@District/DistrictTeamSummaryViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Event/EventAlliancesViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Event/EventAwardsViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Event/EventInfoViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/Team/Team@Event/TeamStatsViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/Team/Team@Event/TeamSummaryViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/Team/TeamMediaCollectionViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/Team/TeamViewController.swift
Removes unowned references from things that could be deallocated - fixes https://github.com/the-blue-alliance/the-blue-alliance-ios/issues/549
> Remove unowned references from non-root view controllers

- the-blue-alliance-ios/View Elements/Base/ReverseSubtitleTableViewCell.swift
Fixes https://github.com/the-blue-alliance/the-blue-alliance-ios/issues/548
> do/catch ReverseSubtitleTableViewCell setHTMLSubtitle method

- the-blue-alliance-ios/View Controllers/Teams/TeamsViewController.swift
> Fix 'Search 0 Teams' in TeamsViewController filter

- the-blue-alliance-ios/Core Data/Event/Event.swift
- the-blue-alliance-ios/Core Data/Event/EventAlliance.swift
- the-blue-alliance-ios/Core Data/Event/EventStatusPlayoff.swift
- the-blue-alliance-ios/Core Data/MyTBA/MyTBAEntity.swift
- the-blue-alliance-ios/View Controllers/Districts/District/DistrictRankingsViewController.swift
- the-blue-alliance-ios/View Controllers/Districts/DistrictsViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Event/EventAlliancesViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Event/EventAwardsViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Event/EventDistrictPointsViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Event/EventRankingsViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Event/Stats/EventTeamStatsViewController.swift
- the-blue-alliance-ios/View Controllers/Events/EventsViewController.swift
- the-blue-alliance-ios/View Controllers/Events/WeekEventsViewController.swift
- the-blue-alliance-ios/View Controllers/Match/MatchesViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/Team/Team@Event/TeamSummaryViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/Team/TeamEventsViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/Team/TeamMediaCollectionViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/TeamsViewController.swift
Finally closes https://github.com/the-blue-alliance/the-blue-alliance-ios/issues/162
> Use KeyPaths for NSPredicate and NSSortDescriptor

- the-blue-alliance-ios/View Controllers/Districts/District/DistrictRankingsViewController.swift
Saw this one showing up in Crashlytics
> Fix crash in district rankings

- the-blue-alliance-ios/View Controllers/Settings/Notifications/NotificationsViewController.swift
> Fix NotificationViewController retain with PushService

- the-blue-alliance-ios/View Elements/Media/PlayerView.swift
> Revert "Use KVO to show Match video player controls (#556)"

- tba-unit-tests/Core Data/Event/WLTTests.swift
- the-blue-alliance-ios.xcodeproj/project.pbxproj
- the-blue-alliance-ios/Core Data/Event/WLT.swift
- the-blue-alliance-ios/View Controllers/Teams/Team/Team@Event/TeamSummaryViewController.swift
- the-blue-alliance-ios/View Elements/Events/RankingCellViewModel.swift
Pulling code from #502 - I think we can make this stand alone, kinda
> Add WLT tests

- the-blue-alliance-ios/View Controllers/Teams/Team/Team@Event/TeamAtEventViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/Team/Team@Event/TeamSummaryViewController.swift
> Split next match/most recent match in to sections

- tba-unit-tests/Core Data/Match/MatchTests.swift
- the-blue-alliance-ios/Core Data/Match/Match.swift
- the-blue-alliance-ios/View Controllers/Teams/Team/Team@Event/TeamSummaryViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/Team/TeamInfoViewController.swift
- the-blue-alliance-ios/View Elements/Base/ReverseSubtitleTableViewCell.swift
Stunning and beautiful. Closes #437. Closes #364.
> Split qual/playoff information in Team@Event. Show overall status at top

- the-blue-alliance-ios/Core Data/MyTBA/MyTBAEntity.swift
> Fix crash when deleting myTBA model

- subtrees/the-blue-alliance-react/app/views/breakdowns/MatchBreakdown2019.js
- subtrees/the-blue-alliance-react/package-lock.json
- the-blue-alliance-ios/Settings.bundle/Acknowledgements.plist
My RN merge got a little bork'd - this should fix it up and put it back in step with the rn repo
> Fix bad RN merge

- tba-unit-tests/View Controllers/Base/Containers/ContainerViewControllerTests.swift
- the-blue-alliance-ios.xcodeproj/project.pbxproj
- the-blue-alliance-ios.xcodeproj/xcshareddata/xcschemes/The Blue Alliance.xcscheme
- the-blue-alliance-ios/Extensions/ContainerViewController+Team.swift
- the-blue-alliance-ios/View Controllers/Base/Containers/ContainerViewController.swift
- the-blue-alliance-ios/View Controllers/Base/Containers/MyTBAContainerViewController.swift
- the-blue-alliance-ios/View Controllers/Base/Data Controllers/TBACollectionViewController.swift
- the-blue-alliance-ios/View Controllers/Base/Data Controllers/TBATableViewController.swift
- the-blue-alliance-ios/View Controllers/Base/Data Controllers/TBAViewController.swift
- the-blue-alliance-ios/View Controllers/Base/SelectTableViewController.swift
- the-blue-alliance-ios/View Controllers/Districts/District/Team@District/TeamAtDistrictViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Event/Stats/EventStatsContainerViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Event/Stats/EventTeamStatsViewController.swift
- the-blue-alliance-ios/View Controllers/Events/YearSelectViewController.swift
- the-blue-alliance-ios/View Controllers/MyTBA/MyTBAViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/Team/Team@Event/TeamAtEventViewController.swift
Should unblock https://github.com/the-blue-alliance/the-blue-alliance-ios/pull/529
> Add system to allow contained view controllers to show bar button items in their container view controller

- the-blue-alliance-ios/Services/StatusService.swift
- the-blue-alliance-ios/StatusDefaults.plist
Should fix 2020 data not showing up oops
> Fix status service not fetching status

- the-blue-alliance-ios/View Controllers/Match/MatchInfoViewController.swift
- the-blue-alliance-ios/View Elements/Match/MatchSummaryView.xib
> Fix match summary background in dark mode

- Podfile
- Podfile.lock
- the-blue-alliance-ios.xcodeproj/project.pbxproj
- the-blue-alliance-ios/App Delegate/AppDelegate.swift
- the-blue-alliance-ios/Settings.bundle/Acknowledgements.plist
- the-blue-alliance-ios/View Controllers/MyTBA/MyTBAViewController.swift
> Bump GoogleSignIn to v5.0.1

- the-blue-alliance-ios/Protocols/Subscribable.swift
- the-blue-alliance-ios/View Controllers/MyTBA/MyTBAPreferenceViewController.swift
> Adopt new iOS 13 adaptive presentation for myTBA preferences

- Frameworks/MyTBAKit/Sources/Classes/MyTBA.swift
- Frameworks/MyTBAKit/Sources/Classes/MyTBAOperation.swift
- Frameworks/MyTBAKit/Sources/Models/MyTBAFavorite.swift
- Frameworks/MyTBAKit/Sources/Models/MyTBAModel.swift
- Frameworks/MyTBAKit/Sources/Models/MyTBAPing.swift
- Frameworks/MyTBAKit/Sources/Models/MyTBAPreferences.swift
- Frameworks/MyTBAKit/Sources/Models/MyTBARegister.swift
- Frameworks/MyTBAKit/Sources/Models/MyTBASubscription.swift
- Frameworks/MyTBAKit/Tests/Classes/MyTBATests.swift
- Frameworks/TBAKit/Sources/TBADistrict.swift
- Frameworks/TBAKit/Sources/TBAEvent.swift
- Frameworks/TBAKit/Sources/TBAMatch.swift
- Frameworks/TBAKit/Sources/TBAStatus.swift
- Frameworks/TBAKit/Sources/TBATeam.swift
- fastlane/metadata/en-US/release_notes.txt
- tba-unit-tests/Info.plist
- the-blue-alliance-ios/Info.plist
- the-blue-alliance-ios/Protocols/Refreshable.swift
- the-blue-alliance-ios/Services/PushService.swift
- the-blue-alliance-ios/View Controllers/MyTBA/MyTBAViewController.swift
Also allow logging out if we get a 404 from the server - should be better all around.
Updated release notes and version for a new release
> Fix myTBA register, remove discardableResult from calls that return Operations

- the-blue-alliance-ios/View Controllers/Settings/Notifications/NotificationsViewController.swift
> Fix copying FCM token crashing on iPad

- the-blue-alliance-ios/View Controllers/Teams/Team/Team@Event/TeamAtEventViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/Team/TeamViewController.swift
Closes https://github.com/the-blue-alliance/the-blue-alliance-ios/issues/412
> Add Media tab to Team@Event view

- the-blue-alliance-ios/View Controllers/Teams/TeamsViewController.swift
Filed a radar to try to get this fixed so we can hold a reference to our search controller - but for now we'll need to get rid of it. I'll have to test how this feels UX-wise
> Fix team search background being white when pulling to refresh in dark mode

- the-blue-alliance-ios/View Controllers/MyTBA/MyTBAViewController.swift
I think this will resolve #713 - I think the myTBA view is being loaded before going to the view and weird stuff is happening.
> Fix crash where myTBA views were loading in the background

- the-blue-alliance-ios/View Controllers/Settings/Notifications/NotificationsViewController.swift
- the-blue-alliance-ios/View Elements/Settings/Notifications/NotificationStatusTableViewCell.xib
> Small fixes to the notification debugging UI

- the-blue-alliance-ios/View Controllers/Base/Data Controllers/Data Sources/CollectionViewDataSource.swift
- the-blue-alliance-ios/View Controllers/Base/Data Controllers/Data Sources/TableViewDataSource.swift
- the-blue-alliance-ios/View Controllers/MyTBA/MyTBATableViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/Team/Team@Event/TeamSummaryViewController.swift
> Fix Team@Event view showing no data when data is loaded

- subtrees/the-blue-alliance-react/package-lock.json
- subtrees/the-blue-alliance-react/package.json
> Update React Native

- Frameworks/TBAData/Resources/TBA.xcdatamodeld/TBA.xcdatamodel/contents
- Frameworks/TBAData/Sources/Event/WLT.swift
- Frameworks/TBAData/Sources/Team/TeamMedia.swift
> Fix insecure transformable Core Data properties

- Frameworks/TBAData/Sources/District/DistrictRanking.swift
- Frameworks/TBAData/Sources/Team/Team.swift
- Frameworks/TBAData/Tests/District/DistrictRankingTests.swift
- Frameworks/TBAData/Tests/Team/TeamTests.swift
- the-blue-alliance-ios.xcodeproj/project.pbxproj
- the-blue-alliance-ios/View Controllers/Base/Data Controllers/TBASearchableTableViewController.swift
- the-blue-alliance-ios/View Controllers/Districts/District/DistrictRankingsViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/TeamsViewController.swift
> Add filter to district rankings

- Frameworks/TBAData/Sources/Protocols/Locatable.swift
- tba-unit-tests/View Controllers/Teams/TeamViewControllerTests.swift
- tba-unit-tests/View Elements/Teams/TeamHeaderViewTests.swift
- the-blue-alliance-ios.xcodeproj/project.pbxproj
- the-blue-alliance-ios/Extensions/UIColor+TBA.swift
- the-blue-alliance-ios/Extensions/UIFont+TBA.swift
- the-blue-alliance-ios/Protocols/ScrollReporter.swift
- the-blue-alliance-ios/Protocols/URLOpener.swift
- the-blue-alliance-ios/View Controllers/Base/Containers/ContainerViewController.swift
- the-blue-alliance-ios/View Controllers/Base/Containers/ScrollableContainerViewController.swift
- the-blue-alliance-ios/View Controllers/Base/Data Controllers/TBACollectionViewController.swift
- the-blue-alliance-ios/View Controllers/Base/Data Controllers/TBATableViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/Team/TeamEventsViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/Team/TeamInfoViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/Team/TeamViewController.swift
- the-blue-alliance-ios/View Elements/Teams/TeamHeaderView.swift
- the-blue-alliance-ios/View Elements/Teams/TeamHeaderViewModel.swift
The animations are a bit weird, but we'll fix it in post...
> Add new header to Team view

- the-blue-alliance-ios/Extensions/UIColor+TBA.swift
- the-blue-alliance-ios/View Elements/Match/MatchSummaryView.swift
Thinning out another PR by merging this separately
> Rename alliance score colors

- the-blue-alliance-ios/View Controllers/Teams/Team/Team@Event/TeamStatsViewController.swift
- the-blue-alliance-ios/View Elements/Events/EventTeamStatCellViewModel.swift
> Fix stats cell names

- the-blue-alliance-ios.xcodeproj/project.pbxproj
- the-blue-alliance-ios/Extensions/UIColor+TBA.swift
- the-blue-alliance-ios/View Controllers/Match/MatchBreakdownViewController.swift
- the-blue-alliance-ios/View Controllers/Match/MatchViewController.swift
- the-blue-alliance-ios/View Elements/Match/Breakdown/MatchBreakdownConfigurator.swift
- the-blue-alliance-ios/View Elements/Match/Breakdown/MatchBreakdownConfigurator2015.swift
- the-blue-alliance-ios/View Elements/Match/Breakdown/MatchBreakdownConfigurator2016.swift
- the-blue-alliance-ios/View Elements/Match/Breakdown/MatchBreakdownConfigurator2017.swift
- the-blue-alliance-ios/View Elements/Match/Breakdown/MatchBreakdownConfigurator2018.swift
- the-blue-alliance-ios/View Elements/Match/Breakdown/MatchBreakdownConfigurator2019.swift
- the-blue-alliance-ios/View Elements/Match/Breakdown/MatchBreakdownView.swift
Rewriting all the match breakdown views after dropping RN
> New Match Breakdown

- the-blue-alliance-ios/View Controllers/Events/Event/EventAlliancesViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Event/EventInfoViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Event/EventViewController.swift
- the-blue-alliance-ios/View Controllers/Match/MatchInfoViewController.swift
- the-blue-alliance-ios/View Controllers/Match/MatchViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/Team/Team@Event/TeamAtEventViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/Team/TeamInfoViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/Team/TeamViewController.swift
> Remove all observeObject calls from init to viewDidLoad

- the-blue-alliance-ios/View Controllers/Events/Event/EventInfoViewController.swift
This should unblock new work in the Event Info VC
> Convert Event Info to diffable data source

- the-blue-alliance-ios/Extensions/NSDiffableDataSourceSnapshot+TBA.swift
> Fix inserting section identifier when it already exists not removing the previous identifier

- Frameworks/TBAData/Sources/Match/Match.swift
- Frameworks/TBAData/Sources/Team/Team.swift
- the-blue-alliance-ios/View Controllers/MyTBA/MyTBATableViewController.swift
> Fix myTBA objects not being sorted properly

- tba-unit-tests/Protocols/RefreshableTests.swift
- the-blue-alliance-ios/Protocols/Refreshable.swift
> Update refresh when canceling refresh if no refresh operations

- the-blue-alliance-ios/Protocols/Stateful.swift
- the-blue-alliance-ios/View Controllers/Districts/District/DistrictEventsViewController.swift
- the-blue-alliance-ios/View Controllers/Districts/District/DistrictRankingsViewController.swift
- the-blue-alliance-ios/View Controllers/Districts/District/DistrictTeamsViewController.swift
- the-blue-alliance-ios/View Controllers/Districts/District/Team@District/DistrictBreakdownViewController.swift
- the-blue-alliance-ios/View Controllers/Districts/DistrictsViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Event/EventAlliancesViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Event/EventAwardsViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Event/EventDistrictPointsViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Event/EventRankingsViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Event/EventTeamsViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Event/Stats/EventStatsViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Event/Stats/EventTeamStatsViewController.swift
- the-blue-alliance-ios/View Controllers/Events/EventsViewController.swift
- the-blue-alliance-ios/View Controllers/Events/WeekEventsViewController.swift
- the-blue-alliance-ios/View Controllers/Events/YearSelectViewController.swift
- the-blue-alliance-ios/View Controllers/Match/MatchBreakdownViewController.swift
- the-blue-alliance-ios/View Controllers/Match/MatchesViewController.swift
- the-blue-alliance-ios/View Controllers/MyTBA/MyTBATableViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/Team/Team@Event/TeamStatsViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/Team/Team@Event/TeamSummaryViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/Team/TeamEventsViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/Team/TeamMediaCollectionViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/TeamsViewController.swift
Part of the work for Search - having no data text be optional will allow views to decide when they do and don't want to show their no data text if their data source is empty
> Change noDataText to be optional

- Frameworks/TBAData/Sources/Event/Event.swift
- Frameworks/TBAData/Tests/Event/EventTests.swift
- the-blue-alliance-ios/View Controllers/MyTBA/MyTBATableViewController.swift
Fixes offseason events sorting wrong, myTBA events sorting incorrectly, and DCMP sorts.
Fixes #790, fixes #783, fixes #784
> Event sorting fixes

- the-blue-alliance-ios/Launch Views/NoDataViewController.swift
- the-blue-alliance-ios/View Elements/Media/PlayerView.swift
> Fix match video light and dark mode colors

- Frameworks/TBAKit/Sources/TBAKit.swift
- Frameworks/TBAKit/Sources/TBAKitOperation.swift
- Frameworks/TBAKit/TBAKit.podspec
- Frameworks/TBAKit/Testing/MockTBAKit.swift
- Frameworks/TBAKit/Tests/TBAKitTestCase.swift
- Frameworks/TBAKit/Tests/TBAKitTests.swift
- Podfile.lock
This should make sure we can do async TBAKit requests - this will be important for Search
> Use new URLSession for each TBAKit request

- fastlane/README.md
- the-blue-alliance-ios/Launch Views/NoDataViewController.swift
- the-blue-alliance-ios/View Elements/Media/PlayerView.swift
> Fix dark mode no data background color

- the-blue-alliance-ios/View Controllers/Base/Data Controllers/TBASearchableTableViewController.swift
> Run filter on main thread, in queue

- the-blue-alliance-ios/App Delegate/AppDelegate.swift
- the-blue-alliance-ios/Services/SearchService.swift
When the app is quit, our view hierarchy isn't setup. We should save the thing we were looking to continue so we can continue once our view hierarchy is setup
> Fix search not pushing from cold launch

- the-blue-alliance-ios/View Elements/Teams/TeamHeaderView.swift
- the-blue-alliance-ios/View Elements/Teams/TeamHeaderViewModel.swift
> Set default colors for some avatars

- Frameworks/TBAData/Sources/Team/Team.swift
- Frameworks/TBAData/Tests/Team/TeamTests.swift
- tba-unit-tests/TBATestCase.swift
- the-blue-alliance-ios/App Delegate/AppDelegate.swift
- the-blue-alliance-ios/Protocols/Refreshable.swift
- the-blue-alliance-ios/Services/SearchService.swift
- the-blue-alliance-ios/View Controllers/Search/SearchViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/TeamsContainerViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/TeamsViewController.swift
> Complete Search refresh if the user backgrounds the app

- the-blue-alliance-ios/View Controllers/Base/SelectTableViewController.swift
> Fix year select check color in Dark Mode

- fastlane/metadata/en-US/release_notes.txt
> Add v2 release notes

- the-blue-alliance-ios/Services/SearchService.swift
- the-blue-alliance-ios/View Controllers/Teams/TeamsViewController.swift
> Fix Teams refresh not executing

- tba-unit-tests/View Controllers/myTBA/MyTBATableViewControllerTests.swift
- the-blue-alliance-ios/Services/SearchService.swift
- the-blue-alliance-ios/View Controllers/Districts/District/DistrictEventsViewController.swift
- the-blue-alliance-ios/View Controllers/Districts/District/DistrictRankingsViewController.swift
- the-blue-alliance-ios/View Controllers/Districts/District/DistrictTeamsViewController.swift
- the-blue-alliance-ios/View Controllers/Districts/District/Team@District/DistrictBreakdownViewController.swift
- the-blue-alliance-ios/View Controllers/Districts/District/Team@District/DistrictTeamSummaryViewController.swift
- the-blue-alliance-ios/View Controllers/Districts/DistrictsViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Event/EventAlliancesViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Event/EventAwardsViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Event/EventDistrictPointsViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Event/EventInfoViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Event/EventRankingsViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Event/EventTeamsViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Event/Stats/EventStatsViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Event/Stats/EventTeamStatsViewController.swift
- the-blue-alliance-ios/View Controllers/Events/WeekEventsViewController.swift
- the-blue-alliance-ios/View Controllers/Events/YearSelectViewController.swift
- the-blue-alliance-ios/View Controllers/Match/MatchBreakdownViewController.swift
- the-blue-alliance-ios/View Controllers/Match/MatchInfoViewController.swift
- the-blue-alliance-ios/View Controllers/Match/MatchesViewController.swift
- the-blue-alliance-ios/View Controllers/MyTBA/MyTBATableViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/Team/Team@Event/TeamStatsViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/Team/Team@Event/TeamSummaryViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/Team/TeamEventsViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/Team/TeamInfoViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/Team/TeamMediaCollectionViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/Team/TeamViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/TeamsViewController.swift
> Only store TBAKit cache headers on successful responses

- the-blue-alliance-ios.entitlements
I forgot we always redirect to `www` zz
> Fix Universial Links

- the-blue-alliance-ios.xcodeproj/project.pbxproj
- the-blue-alliance-ios/View Controllers/Events/EventsContainerViewController.swift
- the-blue-alliance-ios/View Controllers/Match/MatchBreakdownViewController.swift
- the-blue-alliance-ios/View Elements/Match/Breakdown/MatchBreakdownConfigurator2020.swift
- the-blue-alliance-ios/View Elements/Match/Breakdown/MatchBreakdownView.swift
Add the 2020 match breakdown
Uh, it's kinda needed?  😅 
Only locally, but using real data from Week 0 events.
> Add 2020 match breakdown

- the-blue-alliance-ios/App Delegate/AppDelegate.swift
- the-blue-alliance-ios/Info.plist
> Disable analytics collection during debug

- the-blue-alliance-ios/View Elements/Events/Stats/EventStatsConfigurator2020.swift
> Add cell count to 2020 Event Stats

- the-blue-alliance-ios/Services/HandoffService.swift
> Fix HandoffService loading unsaved Event

- the-blue-alliance-ios/View Controllers/Events/Event/EventInfoViewController.swift
This should help us get a sense of how to prioritize iterating on this feature
> Add webcast watch event tracking

- tba-unit-tests/View Controllers/Events/EventViewControllerTests.swift
- the-blue-alliance-ios.xcodeproj/project.pbxproj
- the-blue-alliance-ios/View Controllers/Events/Event/EventInfoViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Event/EventViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Event/Stats/EventInsightsContainerViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Event/Stats/EventInsightsViewController.swift
- the-blue-alliance-ios/View Elements/Events/Stats/EventInsightsConfigurator.swift
- the-blue-alliance-ios/View Elements/Events/Stats/EventInsightsView.swift
- the-blue-alliance-ios/View Elements/Events/Stats/EventStatsConfigurator2016.swift
- the-blue-alliance-ios/View Elements/Events/Stats/EventStatsConfigurator2017.swift
- the-blue-alliance-ios/View Elements/Events/Stats/EventStatsConfigurator2018.swift
- the-blue-alliance-ios/View Elements/Events/Stats/EventStatsConfigurator2019.swift
- the-blue-alliance-ios/View Elements/Events/Stats/EventStatsConfigurator2020.swift
> Rename 'Event Stats' to 'Event Insights'

- tba-unit-tests/View Controllers/Events/EventViewControllerTests.swift
- the-blue-alliance-ios/View Controllers/Districts/District/DistrictViewController.swift
- the-blue-alliance-ios/View Controllers/Districts/District/Team@District/TeamAtDistrictViewController.swift
- the-blue-alliance-ios/View Controllers/Districts/DistrictsContainerViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Event/EventAlliancesViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Event/EventAwardsViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Event/EventDistrictPointsViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Event/EventViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Event/Stats/EventInsightsContainerViewController.swift
- the-blue-alliance-ios/View Controllers/Events/EventsContainerViewController.swift
- the-blue-alliance-ios/View Controllers/Events/YearSelectViewController.swift
- the-blue-alliance-ios/View Controllers/Match/MatchViewController.swift
- the-blue-alliance-ios/View Controllers/MyTBA/MyTBAViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/Team/Team@Event/TeamAtEventViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/Team/TeamViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/TeamsContainerViewController.swift
> Convert Crashlytics info from events to logs

- Frameworks/TBAData/Sources/Event/Webcast.swift
> Support direct_link webcasts in Event

- Podfile.lock
- spotlight-index/Info.plist
- tba-unit-tests/Info.plist
- the-blue-alliance-ios/Info.plist
> Bump Firebase

- Podfile
- Podfile.lock
- the-blue-alliance-ios.xcodeproj/project.pbxproj
- the-blue-alliance-ios.xcodeproj/xcshareddata/xcschemes/The Blue Alliance.xcscheme
- the-blue-alliance-ios/App Delegate/AppDelegate.swift
- the-blue-alliance-ios/Info.plist
- the-blue-alliance-ios/Settings.bundle/Acknowledgements.plist
A little bit over-scoped but also fixes an iOS 14 crash when setting up our Core Data stack with the new Spotlight Indexer changes
Closes #885
> Migrate from Fabric + Crashlytics to FirebaseCrashlytics

- the-blue-alliance-ios/View Controllers/Base/Data Controllers/Data Sources/CollectionViewDataSource.swift
- the-blue-alliance-ios/View Controllers/Base/Data Controllers/Data Sources/TableViewDataSource.swift
- the-blue-alliance-ios/View Controllers/Districts/District/DistrictRankingsViewController.swift
- the-blue-alliance-ios/View Controllers/Districts/District/DistrictTeamsViewController.swift
- the-blue-alliance-ios/View Controllers/Districts/DistrictsViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Event/EventAwardsViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Event/EventDistrictPointsViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Event/EventInfoViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Event/EventRankingsViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Event/Stats/EventInsightsViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Event/Stats/EventTeamStatsViewController.swift
- the-blue-alliance-ios/View Controllers/Events/EventsViewController.swift
- the-blue-alliance-ios/View Controllers/Events/WeekEventsViewController.swift
- the-blue-alliance-ios/View Controllers/Match/MatchBreakdownViewController.swift
- the-blue-alliance-ios/View Controllers/Match/MatchesViewController.swift
- the-blue-alliance-ios/View Controllers/MyTBA/MyTBATableViewController.swift
- the-blue-alliance-ios/View Controllers/Search/SearchViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/Team/Team@Event/TeamStatsViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/Team/Team@Event/TeamSummaryViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/Team/TeamInfoViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/Team/TeamMediaCollectionViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/TeamsViewController.swift
Probably going to push this through CI without fixing the snapshot tests, since we should be able to iterate on this
> Fix diffable data source crashes in iOS 15

- Frameworks/TBAData/Sources/Event/WLT.swift
- Frameworks/TBAData/Tests/Event/WLTTests.swift
> Fixes Team@Event crash with WLT row hash differing

- tba-unit-tests/Services/HandoffServiceTests.swift
- the-blue-alliance-ios/App Delegate/AppDelegate.swift
- the-blue-alliance-ios/Services/HandoffService.swift
> Fix constructing root view controller hiearchy before persistent store is loaded from handoff flow
