- the-blue-alliance-ios/AppDelegate.m
- the-blue-alliance-ios/Base.lproj/Main.storyboard
- the-blue-alliance-ios/TBANavigationControllerDelegate.h
- the-blue-alliance-ios/TBANavigationControllerDelegate.m
- the-blue-alliance.xcodeproj/project.pbxproj
- the-blue-alliance.xcworkspace/contents.xcworkspacedata
To help with text clipping (either the back button text, or the navigation bar title) this sets up a delegate object (retained by the app delegate) to modify the back button item to be a back button without text
> Remove back button title text

- the-blue-alliance-ios/Base.lproj/Main.storyboard
- the-blue-alliance-ios/TBAMatchTableViewCell.m
Makes sure the subviews in the match cell have the same background color during the selection state (screenshot attached), as opposed to the grey color. The other solution here is to disable the selection state for the match cells.
> Keep previous subview colors in match cell during selection

- the-blue-alliance-ios/TBAMatchTableViewCell.m
Web/Android does the same thing - no "winners" in 2015 except for the finals
> Removes borders for 'winning' matches in 2015

- Podfile.lock
- the-blue-alliance-ios/EventsViewController.m
- the-blue-alliance-ios/Models/Event.h
- the-blue-alliance-ios/Models/Event.m
Created an `EventWeek` class that holds a number of static methods (err class methods) that
determines what event week is for a given date. `EventViewController` uses this new class to
pre-select the current event week when first visiting event list.
Admittedly these methods are basically a complete rip off of what the android app has.
https://github.com/the-blue-alliance/the-blue-alliance-android/blob/c4948c3a560e3b73833197b92d24295027004afe/android/src/main/java/com/thebluealliance/androidclient/helpers/EventHelper.java#L98
https://github.com/the-blue-alliance/the-blue-alliance-android/blob/c4948c3a560e3b73833197b92d24295027004afe/android/src/main/java/com/thebluealliance/androidclient/helpers/EventHelper.java#L98
> [closes #39] Auto select event week.

- the-blue-alliance-ios/EventsStoryboard.storyboard
- the-blue-alliance-ios/TBAInfoTableViewCell.h
- the-blue-alliance-ios/TBAInfoTableViewCell.m
- the-blue-alliance-ios/TBAInfoViewController.m
- the-blue-alliance-ios/TeamsStoryboard.storyboard
- the-blue-alliance.xcodeproj/project.pbxproj
Looking for feedback - might need to take another pass at how the Team view looks since there's more info there. But I think the Event view is pretty good.
> Modify info view headers

- Podfile
- Podfile.lock
- the-blue-alliance-ios/AppDelegate.m
We no longer need it since we took out the action of opening an event/team location in Google Maps
> Removes the Google Maps library

- the-blue-alliance-ios/AppDelegate.m
- the-blue-alliance-ios/Base Classes/TBAEventsViewController.m
After building a downloader that hooked in to inserts for stub team objects, I realized it was way more complicated than it needed to be, and making far too many network requests. I suggest we just attempt to refresh teams on initial launch to fix the current stub team states. We could also set a last fetched date in NSUserDefaults and if we see we haven't done a batch refresh in a certain period to keep things in sync.
> [Closes #55] Setup initial background fetch for all teams

- Podfile.lock
- the-blue-alliance-ios/Team+Fetch.m
When paging through teams with the Last-Modified header, we won't get any data back if a page for the teams endpoint hasn't been modified. However, the only way for us to tell if we've hit a page that doesn't have any teams is if we get back no data (an empty page still gives us a 200 and a Last-Modified back). This is a simple fix, but we store the max page we see for the teams paging call, and make sure we always check up to at least that point.
> Fix team pages refresh

- tba-unit-tests/Operations/myTBA/MyTBASignOutOperation_Tests.swift
- the-blue-alliance-ios.xcodeproj/project.pbxproj
- the-blue-alliance-ios/Frameworks/MyTBAKit/Models/MyTBAFavorite.swift
- the-blue-alliance-ios/Frameworks/MyTBAKit/Models/MyTBARegister.swift
- the-blue-alliance-ios/Frameworks/MyTBAKit/Models/MyTBASubscription.swift
- the-blue-alliance-ios/Frameworks/MyTBAKit/MyTBA.swift
- the-blue-alliance-ios/Operations/myTBA/MyTBASignOutOperation.swift
- the-blue-alliance-ios/Services/PushService.swift
- the-blue-alliance-ios/TestAppDelegate.swift
- the-blue-alliance-ios/View Controllers/MyTBA/MyTBAViewController.swift
- the-blue-alliance-ios/main.swift
Making unregister a synchronous action via an action and an activity spinner, since signing out of Google makes it where myTBA is unauthenticated, and we need to be authenticated when we hit that unregister endpoint.  Closes #175
> Add myTBA unregister as syncronous action

- the-blue-alliance-ios/Frameworks/MyTBAKit/Models/MyTBARegister.swift
The register response returns a 304, which isn't a 200, and incorrectly tells the retry service for registering push notifications that it failed. After a minute, it retries, and attempts to register with it's retry service a second time and crashes.
This fixes by just casing the response code from a string to an int, and doing the same check we were doing before (>= 400 is an error)
> Fix crash where already-registered myTBA would crash after 1 min

- tba-unit-tests/Protocols/Refreshable_Tests.swift
- the-blue-alliance-ios/Protocols/Refreshable.swift
- the-blue-alliance-ios/View Controllers/Base/SelectTableViewController.swift
- the-blue-alliance-ios/View Controllers/Districts/DistrictEventsViewController.swift
- the-blue-alliance-ios/View Controllers/Districts/DistrictRankingsViewController.swift
- the-blue-alliance-ios/View Controllers/Districts/DistrictsViewController.swift
- the-blue-alliance-ios/View Controllers/Districts/Team@District/DistrictBreakdownViewController.swift
- the-blue-alliance-ios/View Controllers/Districts/Team@District/DistrictTeamSummaryViewController.swift
- the-blue-alliance-ios/View Controllers/Events/EventAlliancesViewController.swift
- the-blue-alliance-ios/View Controllers/Events/EventAwardsViewController.swift
- the-blue-alliance-ios/View Controllers/Events/EventDistrictPointsViewController.swift
- the-blue-alliance-ios/View Controllers/Events/EventInfoViewController.swift
- the-blue-alliance-ios/View Controllers/Events/EventRankingsViewController.swift
- the-blue-alliance-ios/View Controllers/Events/EventsViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Match/MatchBreakdownViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Match/MatchInfoViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Match/MatchesViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Stats/EventStatsViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Stats/EventTeamStatsViewController.swift
- the-blue-alliance-ios/View Controllers/Events/WeekEventsViewController.swift
- the-blue-alliance-ios/View Controllers/Events/YearSelectViewController.swift
- the-blue-alliance-ios/View Controllers/MyTBA/MyTBATableViewController.swift
- the-blue-alliance-ios/View Controllers/Settings/SettingsViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/TeamEventsViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/TeamInfoViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/TeamMediaCollectionViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/TeamStatsViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/TeamSummaryViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/TeamsViewController.swift
- Add WeeksSelectTableViewController to handle refresh logic for EventWeekSelectViewController
- Makes `refreshKey` nullable, for `SelectTableViewController`
- Remove default protocol implementation of `automaticRefreshInterval` and `automaticRefreshEndDate`
- Make `lastRefresh` date private
- Add `clearSuccessfulRefreshes` to clear all previous refreshes
- Call `clearSuccessfulRefreshes` during `Delete Network Cache` in Settings
- Update Refreshable tests for new behavior
> Fix year select crash

- the-blue-alliance-ios/View Elements/Awards/AwardTableViewCell.swift
- the-blue-alliance-ios/View Elements/Events/EventAllianceTableViewCell.swift
- the-blue-alliance-ios/View Elements/Info/InfoTableViewCell.swift
- the-blue-alliance-ios/View Elements/Match/MatchView.swift
This fixes Event Alliances not removing the default cell content - the cells were never "reused", they were just init'd for the first time. This goes with the safer (and previous) route of removing existing info when setting up a cell.
> Remove view clean from prepareForReuse to configureCell

- the-blue-alliance-ios/Core Data/Award.swift
- the-blue-alliance-ios/Core Data/DistrictEventPoints.swift
- the-blue-alliance-ios/Core Data/DistrictRanking.swift
- the-blue-alliance-ios/Core Data/EventAlliance.swift
- the-blue-alliance-ios/Core Data/EventRanking.swift
- the-blue-alliance-ios/Core Data/EventTeamStat.swift
- the-blue-alliance-ios/Core Data/Media.swift
- the-blue-alliance-ios/View Controllers/Districts/DistrictEventsViewController.swift
- the-blue-alliance-ios/View Controllers/Districts/DistrictRankingsViewController.swift
- the-blue-alliance-ios/View Controllers/Districts/Team@District/DistrictBreakdownViewController.swift
- the-blue-alliance-ios/View Controllers/Districts/Team@District/DistrictTeamSummaryViewController.swift
- the-blue-alliance-ios/View Controllers/Events/EventAlliancesViewController.swift
- the-blue-alliance-ios/View Controllers/Events/EventAwardsViewController.swift
- the-blue-alliance-ios/View Controllers/Events/EventDistrictPointsViewController.swift
- the-blue-alliance-ios/View Controllers/Events/EventRankingsViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Match/MatchesViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Stats/EventTeamStatsViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/TeamMediaCollectionViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/TeamStatsViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/TeamSummaryViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/TeamsViewController.swift
Previously in a lot of places we were setting up model relationships twice. Once in the `insert` method, and then once in the TBAKit callback. This is problematic when we a 304 from the API, since we will get back an empty array. Our TBAKit callback won't insert any objects, but we'll overwrite the model's relationship. An example of this is in the District Events view
`backgroundDistrict.events = Set(localEvents ?? []) as NSSet`
If we didn't get a modified response from the API, `localEvents` will be nil (or empty), and we'll overwrite all the previous relationships for Events in that district.
This makes our `insert` model the source of truth for setting up most relationships. Other places where we're not passing a Core Data object on inserts we're doing append-only for setting up …
> Fix model relationships being overwritten by empty cache responses

- the-blue-alliance-ios/Core Data/Media.swift
- the-blue-alliance-ios/View Controllers/Districts/DistrictEventsViewController.swift
- the-blue-alliance-ios/View Controllers/Districts/DistrictRankingsViewController.swift
- the-blue-alliance-ios/View Controllers/Districts/DistrictsViewController.swift
- the-blue-alliance-ios/View Controllers/Districts/Team@District/DistrictBreakdownViewController.swift
- the-blue-alliance-ios/View Controllers/Districts/Team@District/DistrictTeamSummaryViewController.swift
- the-blue-alliance-ios/View Controllers/Events/EventAlliancesViewController.swift
- the-blue-alliance-ios/View Controllers/Events/EventAwardsViewController.swift
- the-blue-alliance-ios/View Controllers/Events/EventDistrictPointsViewController.swift
- the-blue-alliance-ios/View Controllers/Events/EventRankingsViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Match/MatchBreakdownViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Match/MatchInfoViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Match/MatchesViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Stats/EventStatsViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Stats/EventTeamStatsViewController.swift
- the-blue-alliance-ios/View Controllers/Events/WeekEventsViewController.swift
- the-blue-alliance-ios/View Controllers/Events/YearSelectViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/TeamEventsViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/TeamMediaCollectionViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/TeamStatsViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/TeamSummaryViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/TeamsViewController.swift
I'll probably ship this when I can confirm that we're deleting old events for year, and deleting old teams. Should be simple-ish.
> Overwrite old data during refresh

- tba-unit-tests/Core Data/Event/Event_Tests.swift
- the-blue-alliance-ios/Core Data/Event.swift
Adds a condition for `hybridType` that handles offseason events to group offseason events together by months. Fixes #264
> Fix team events not grouping offseason events by month

- Podfile.lock
- tba-unit-tests/Core Data/Match/MatchAlliance_Tests.swift
- tba-unit-tests/Core Data/Match/MatchVideo_Tests.swift
- tba-unit-tests/Core Data/Match/Match_Tests.swift
- tba-unit-tests/Core Data/Team/TeamKey_Tests.swift
- the-blue-alliance-ios.xcodeproj/project.pbxproj
- the-blue-alliance-ios.xcodeproj/xcshareddata/xcschemes/The Blue Alliance.xcscheme
- the-blue-alliance-ios/Core Data/Match.swift
- the-blue-alliance-ios/Core Data/MatchAlliance.swift
- the-blue-alliance-ios/Core Data/MatchVideo.swift
- the-blue-alliance-ios/Core Data/TBA.xcdatamodeld/TBA.xcdatamodel/contents
- the-blue-alliance-ios/Core Data/TeamKey.swift
- the-blue-alliance-ios/View Controllers/Events/Match/MatchBreakdownViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Match/MatchViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Match/MatchesViewController.swift
- the-blue-alliance-ios/View Controllers/MyTBA/MyTBATableViewController.swift
- the-blue-alliance-ios/View Elements/Match/MatchViewModel.swift
This is a bit of a tech debt thing, but also the first step in removing all usages of `Team.insert(withKey:)` (#265). Core Data can't handle this migration for us (obviously), but we should be able to migrate our old objects to this new format without any problems.
- Update TBAKit to 2.0.8
- Remove `redAlliance` and `blueAlliance` from Match
- Remove `redBreakdown` and `blueBreakdown` from Match
- Remove `redDQTeamKeys` and `blueDQTeamKeys` from Match
- Remove `redScore` and `blueSurrogateTeamKeys` from Match
- Add MatchAlliance Core Data model, to represent `alliances` on a `Match`
- Nullify missing Match values when updating a model from a TBAKit object
TODO, before merging
> Store MatchAlliances on Match, store breakdown on Match as JSON

- tba-unit-tests/Core Data/Event/EventTests.swift
- tba-unit-tests/Core Data/Match/MatchAllianceTests.swift
- tba-unit-tests/Core Data/Match/MatchTests.swift
- tba-unit-tests/Core Data/Match/MatchVideoTests.swift
- the-blue-alliance-ios/Core Data/Event/Event.swift
- the-blue-alliance-ios/Core Data/Match/Match.swift
- the-blue-alliance-ios/Core Data/MyTBA/Favorite.swift
- the-blue-alliance-ios/Core Data/MyTBA/MyTBAEntity.swift
- the-blue-alliance-ios/Core Data/MyTBA/Subscription.swift
- the-blue-alliance-ios/Core Data/TBA.xcdatamodeld/TBA.xcdatamodel/contents
- the-blue-alliance-ios/View Controllers/Events/Match/MatchBreakdownViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Match/MatchInfoViewController.swift
This is part of the myTBA work - when loading data from myTBA, we get keys for objects. Sometimes that's a Match key. We don't want to chain network requests together, so this allows Matches to be saved without an Event associated with them. The only difference is when loading an Event for the first time after loading myTBA, that Match won't show up in the list (we can handle this in the myTBA fetching code)
> Make Event optional on a Match

- tba-unit-tests/Core Data/CoreDataTestCase.swift
- tba-unit-tests/Core Data/District/DistrictRankingTests.swift
- tba-unit-tests/Core Data/District/DistrictTests.swift
- tba-unit-tests/Core Data/Event/EventTests.swift
- tba-unit-tests/Core Data/Team/TeamTests.swift
- tba-unit-tests/Frameworks/TBAKit/TBAEventTests.swift
- tba-unit-tests/View Controllers/Districts/DistrictViewControllerTests.swift
- the-blue-alliance-ios/Core Data/Event/Event.swift
Adds tests for `Event.dateString` - which is failing on CI because of time zones.
> Add Event dateString tests

- the-blue-alliance-ios/View Controllers/Match/MatchBreakdownViewController.swift
- the-blue-alliance-ios/View Controllers/Match/MatchInfoViewController.swift
Apparently we didn't hit all of the references assuming a Match has an Event attached to it - this might fix some of our flaky tests as well
> Fix Match view controller crashes assuming Matches have Events

- the-blue-alliance-ios.xcodeproj/project.pbxproj
- the-blue-alliance-ios/Extensions/URL+Reachable.swift
- the-blue-alliance-ios/Protocols/Refreshable.swift
- the-blue-alliance-ios/Services/ReactNativeService.swift
- the-blue-alliance-ios/View Controllers/Base/Data Controllers/TBAReactNativeViewController.swift
- the-blue-alliance-ios/View Controllers/Base/Data Controllers/TBAViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Event/Stats/EventStatsViewController.swift
- the-blue-alliance-ios/View Controllers/Match/MatchBreakdownViewController.swift
- the-blue-alliance-ios/View Controllers/Match/MatchInfoViewController.swift
- The `try?`s we were using the return values for weren't getting checked properly, which fixes a handful of bugs
- Removed the `ReactNative` protocol (god bless) in favor of having all that logic self-contained in `TBAReactNativeViewController`
- Only delete our bundle if we're successfully unpacked it - this means a React Native bundle could sit around for whatever the `retryTime` is on that `ReactNativeService`, but that's like 15min of having a few MB sitting around - not a big deal.
- Added `TBAReactNativeViewController`, which handles the view lifecycle of React Native views MUCH better (closes #261)
- Made `sourceURL` for React Native optional, since this was either buggy or crashing in debug builds - we should probably add more safety, but this should work for now
- Renamed …
> React Native improvements

- the-blue-alliance-ios/View Controllers/Districts/District/DistrictViewController.swift
- the-blue-alliance-ios/View Controllers/Districts/District/Team@District/TeamAtDistrictViewController.swift
- the-blue-alliance-ios/View Controllers/Districts/DistrictsContainerViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Event/EventAlliancesViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Event/EventAwardsViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Event/EventDistrictPointsViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Event/EventViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Event/Stats/EventStatsContainerViewController.swift
- the-blue-alliance-ios/View Controllers/Events/EventsContainerViewController.swift
- the-blue-alliance-ios/View Controllers/Events/YearSelectViewController.swift
- the-blue-alliance-ios/View Controllers/Match/MatchViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/Team/Team@Event/TeamAtEventViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/Team/TeamViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/TeamsContainerViewController.swift
In an attempt to track down the illusive Team@Event AwardRecipient crash, we're going to add some logging so we can figure out what team/event users are looking at when they're experiencing a crash.
> Add log events for container views

- the-blue-alliance-ios/View Elements/Info/InfoCellViewModel.swift
Remove team motto from the Team view, since we're moving away from supporting Team mottos. Eventually we can drop this from the data model.
> Remove team motto from Team view

- tba-unit-tests/Core Data/Award/AwardRecipientTests.swift
- the-blue-alliance-ios/Core Data/Award/AwardRecipient.swift
iOS-side fix for https://github.com/the-blue-alliance/the-blue-alliance/issues/2399 - we're seeing a lot of crashes where `Award_Recipient` objects coming back from the API have no `team_key` or `awardee`. This allows the creation of an empty `AwardRecipient` object, with neither of those fields populated.
Note: This will be weird because we'll have a bunch of Awards attached to this one null `AwardRecipient`. But maybe it's not weird at all. Maybe it's just quirky, in a kinda cute rom-com leading lady sort of way.
> Remove validation to allow empty AwardRecipient objects

- the-blue-alliance-ios/View Controllers/Teams/TeamsViewController.swift
Fixes the count in the search bar placeholder being incorrect in some cases (ex: searching, pushing to a team, going backwards, clearing search text). `controllerDidChangeContent` wasn't being called properly, so our `updateInterface` wasn't being called properly. This adds the `updateInterface` call to the `updateSearchResults` delegate method, which should be cleaner.
Closes #428
> Fix team search bar count showing up incorrectly

- tba-unit-tests/Core Data/Match/MatchAllianceTests.swift
- tba-unit-tests/Core Data/Match/MatchTests.swift
- the-blue-alliance-ios/Core Data/Match/Match.swift
- the-blue-alliance-ios/Core Data/Match/MatchAlliance.swift
- the-blue-alliance-ios/View Elements/Match/MatchSummaryView.swift
- the-blue-alliance-ios/View Elements/Match/MatchViewModel.swift
Fixes team number bolding when viewing a filtered list of matches for a team. Add a striketrhough like the web has for teams that were DQ'd in a match (closes #436)
I attempted to add the DQ feature and realized the bolding was also broken 🤷‍♂️ 
Wrote tests for new Core Data extensions, manually tested cell changes (note: these should get snapshot tests eventually)
> Fixes team number bolding in match cells, adds DQ strikethrough to match cells

- .travis.yml
- tba-unit-tests/Core Data/Event/EventRankingTests.swift
- the-blue-alliance-ios/Core Data/Event/EventRanking.swift
- the-blue-alliance-ios/Core Data/TBA.xcdatamodeld/TBA.xcdatamodel/contents
- the-blue-alliance-ios/Frameworks/TBAKit/Sources/TBAEvent.swift
- the-blue-alliance-ios/View Controllers/Teams/Team/Team@Event/TeamSummaryViewController.swift
- the-blue-alliance-ios/View Elements/Events/RankingCellViewModel.swift
Show `extraStats`/`sortInfo` in `rankingInfoString` in ranking cell (helpful because we'll show RP). Additionally for the 2015 cells, add the qualAverage where WLT would be so it's scanable(ish)
> Show extraStats/sortInfo in raking cells, show qualAverage in 2015 cells

- fastlane/Fastfile
I think we're going to move to a new system where betas are a little more chill and less noisy. We should figure out how to automate shipping to the App Store from a TestFlight build so we can still automate GitHub releases, but for now we don't need to upload artifacts and set changelogs for beta builds.
> Don't create GitHub releases or git tags for betas

- .travis.yml
Second curtain isn't uploading snapshot test diffs because we're installing it globally and trying to run it via bundler.
> Fix second curtain

- the-blue-alliance-ios/View Controllers/Teams/Team/Team@Event/TeamSummaryViewController.swift
`TeamSummaryViewController` was never being deallocated because of a retain cycle with it's `contextObserver`. This should fix that.
> Fix TeamSummaryViewController never being deallocated

- the-blue-alliance-ios/Protocols/Refreshable.swift
- the-blue-alliance-ios/Protocols/Stateful.swift
- the-blue-alliance-ios/View Controllers/Base/Containers/ContainerViewController.swift
- the-blue-alliance-ios/View Controllers/Base/Data Controllers/Data Sources/CollectionViewDataSource.swift
- the-blue-alliance-ios/View Controllers/Base/Data Controllers/Data Sources/TableViewDataSource.swift
- the-blue-alliance-ios/View Controllers/Base/Data Controllers/TBACollectionViewController.swift
- the-blue-alliance-ios/View Controllers/Base/Data Controllers/TBATableViewController.swift
- the-blue-alliance-ios/View Controllers/Base/Data Controllers/TBAViewController.swift
- the-blue-alliance-ios/View Controllers/Districts/District/DistrictEventsViewController.swift
- the-blue-alliance-ios/View Controllers/Districts/District/DistrictRankingsViewController.swift
- the-blue-alliance-ios/View Controllers/Districts/District/DistrictTeamsViewController.swift
- the-blue-alliance-ios/View Controllers/Districts/District/Team@District/DistrictBreakdownViewController.swift
- the-blue-alliance-ios/View Controllers/Districts/DistrictsViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Event/EventAlliancesViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Event/EventAwardsViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Event/EventDistrictPointsViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Event/EventRankingsViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Event/EventTeamsViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Event/Stats/EventStatsViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Event/Stats/EventTeamStatsViewController.swift
- the-blue-alliance-ios/View Controllers/Events/WeekEventsViewController.swift
- the-blue-alliance-ios/View Controllers/Events/YearSelectViewController.swift
- the-blue-alliance-ios/View Controllers/Match/MatchBreakdownViewController.swift
- the-blue-alliance-ios/View Controllers/Match/MatchesViewController.swift
- the-blue-alliance-ios/View Controllers/MyTBA/MyTBATableViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/Team/Team@Event/TeamStatsViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/Team/Team@Event/TeamSummaryViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/Team/TeamEventsViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/Team/TeamMediaCollectionViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/TeamsViewController.swift
- Handle removing no data views during refresh automatically
- Remove non-granular reloads in `noDataReload` - don't reload data, show/hide no data view if appropriate
- Fix refreshing non-stateful views (calling `noDataReload` actions) after refreshes
- Only process view changes on foreground view controllers
- Update background'd view controllers to sync view changes on `viewWillAppear`
- Launch a fresh install
- Navigate to an Event
- Load Event Rankings, notice team names are missing
- View Event Teams
- Navigate back to Event Rankings, notice team names are now populated, since we refreshed the table view in `viewWillAppear`
- Change Team Media refreshing to gracefully load in images
> Process collection view section updates, only update views when visible, modify team media refresh

- tba-unit-tests/Protocols/RefreshableTests.swift
- the-blue-alliance-ios/View Controllers/Base/Data Controllers/Data Sources/CollectionViewDataSource.swift
- the-blue-alliance-ios/View Controllers/Base/Data Controllers/Data Sources/TableViewDataSource.swift
- the-blue-alliance-ios/View Controllers/Teams/TeamsViewController.swift
Related to #589 - when we're processing updates for our table views and collection views, let's not capture self
> Use weak self when updating table views and collection views

- the-blue-alliance-ios/App Delegate/AppDelegate.swift
- the-blue-alliance-ios/Info.plist
This appears to be working properly - the right breakpoints appear to be being hit in the `#if DEBUG` bit, and when running in debug I don't get the usual `[Crashlytics] Version 3.12.0` output, where I do get it still during a Release build. Closes #381
> Disable Crashlytics in debug builds

- tba-unit-tests/Core Data/CoreDataTestCase.swift
- tba-unit-tests/Core Data/Event/EventRankingStatInfoTests.swift
- tba-unit-tests/Core Data/Event/EventRankingStatTests.swift
- tba-unit-tests/Core Data/Event/EventRankingTests.swift
- tba-unit-tests/Extensions/NSSet+OnlyTests.swift
- tba-unit-tests/XCTestCase+FatalError.swift
- the-blue-alliance-ios.xcodeproj/project.pbxproj
- the-blue-alliance-ios.xcodeproj/xcshareddata/xcschemes/tba-unit-tests.xcscheme
- the-blue-alliance-ios/App Delegate/TestAppDelegate.swift
- the-blue-alliance-ios/Core Data/Event/EventRanking.swift
- the-blue-alliance-ios/Core Data/Event/EventRankingStat.swift
- the-blue-alliance-ios/Core Data/Event/EventRankingStatInfo.swift
- the-blue-alliance-ios/Core Data/Protocols/Managed.swift
- the-blue-alliance-ios/Core Data/TBA.xcdatamodeld/TBA.xcdatamodel/contents
- the-blue-alliance-ios/Extensions/NSSet+Only.swift
Convert the old `extraStatsNames`/`extraStatsValues` and `tiebreakerNames`/`tiebreakerValues` to `extraStatsInfo`/`extraStats` and `sortOrdersInfo`/`sortOrders`, and make them relationships on the model to `EventRankingStat` and `EventRankingStatsInfo` objects instead of string arrays.
The new `EventRankingStatsInfo` model stores precision as well as name, which means our `rankingInfoString` will always show the right precision when display these stats. The `EventRankingStat` is because storing the value on the `EventRankingStatsInfo`, or having some `EventRankingStat` that referred to a `EventRankingStatsInfo` and doing the book keeping for cleanup got WILDLY complicated. We have to keep two ordered arrays in sync, but we get this for "free" with `updateToManyRelationship`, so it's not a …
> Convert EventRanking tiebraker to EventRankingStat/EventRankingStatsInfo

- the-blue-alliance-ios/Core Data/TBA.xcdatamodeld/TBA.xcdatamodel/contents
Fixes #629 - we need to merge once we start rolling our iOS 13 update
We should also figure out why `syncable="YES"` is removed automatically - my guess is this is related to the new Core Data syncing via CloudKit stuff.
> [DNM] [ios13] Fix insecure transformable Core Data properties

- the-blue-alliance-ios/Core Data/TBA.xcdatamodeld/TBA.xcdatamodel/contents
This causes a crash when using the default suggestion
```
2019-10-03 20:39:31.646802-0400 The Blue Alliance[9386:81014] [error] error: SQLCore dispatchRequest: exception handling request: <NSSQLSaveChangesRequestContext: 0x7b2c00020df0> , Object of class WLT is not among allowed top level class list (
NSArray,
NSDictionary,
NSSet,
NSString,
NSNumber,
NSDate,
NSData,
NSURL,
NSUUID,
NSNull
) with userInfo of (null)
CoreData: error: SQLCore dispatchRequest: exception handling request: <NSSQLSaveChangesRequestContext: 0x7b2c00020df0> , Object of class WLT is not among allowed top level class list (
NSArray,
NSDictionary,
NSSet,
NSString,
NSNumber,
NSDate,
NSData,
NSURL,
NSUUID,
NSNull
) with userInfo of (null)
2019-10-03 20:39:31.772556-0400 The Blue Alliance[9386:81014] *** Terminating app …
```
> Revert "[ios13] Fix insecure transformable Core Data properties (#632)"

- the-blue-alliance-ios/Extensions/ContainerViewController+Team.swift
- the-blue-alliance-ios/View Controllers/Districts/District/Team@District/TeamAtDistrictViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/Team/Team@Event/TeamAtEventViewController.swift
Not sure how long this has been broken for - probably since the TBAKitOperation PR I'd imagine.
> Fix broken push from Team@Event or Team@District -> Team

- fastlane/Fastfile
This should fix the problem where our `deliver` step is waiting for our build to finish processing, which causes our job to time out on CI and we never post to Slack or create a GitHub release.
> Move fastlane deliver step in app_store lane after GH release and Slack message

- Frameworks/TBAData/Sources/Event/Event.swift
- Frameworks/TBAData/Tests/Event/EventTests.swift
- the-blue-alliance-ios/View Controllers/Teams/Team/Team@Event/TeamAtEventViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/Team/Team@Event/TeamSummaryViewController.swift
Add `InfoTableViewCell` to the Team@Event view, which should allow showing team name and location in the Team@Event view, and eventually avatar.
Also, removed the awards cell from the Team@Event view - there's already a tab, so we don't really need to duplicate that information
Closes https://github.com/the-blue-alliance/the-blue-alliance-ios/issues/539
> Support showing team name/location in Team@Event view

- the-blue-alliance-ios/View Controllers/Base/Data Controllers/Data Sources/TableViewDataSource.swift
- the-blue-alliance-ios/View Controllers/Districts/District/DistrictRankingsViewController.swift
- the-blue-alliance-ios/View Controllers/Districts/DistrictsViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Event/EventAwardsViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Event/EventDistrictPointsViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Event/EventRankingsViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Event/Stats/EventTeamStatsViewController.swift
- the-blue-alliance-ios/View Controllers/Events/EventsViewController.swift
- the-blue-alliance-ios/View Controllers/Match/MatchesViewController.swift
- the-blue-alliance-ios/View Controllers/MyTBA/MyTBATableViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/Team/Team@Event/TeamSummaryViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/TeamsViewController.swift
This should allow our simpler table views to use `TableViewDataSource`
> Allow Stateless view controllers to use TableViewDataSource

- the-blue-alliance-ios/View Controllers/Base/Containers/ContainerViewController.swift
- the-blue-alliance-ios/View Controllers/Districts/DistrictsViewController.swift
- the-blue-alliance-ios/View Controllers/Events/Event/Stats/EventTeamStatsViewController.swift
- the-blue-alliance-ios/View Controllers/Events/EventsViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/Team/TeamMediaCollectionViewController.swift
I'm not in love with this solution but it'll work for now
Closes #705
> Fix selection modals not reloading underlying views in iOS 13

- the-blue-alliance-ios/View Controllers/Match/MatchInfoViewController.swift
- the-blue-alliance-ios/View Elements/Match/MatchSummaryView.swift
- the-blue-alliance-ios/View Elements/Match/MatchSummaryView.xib
- the-blue-alliance-ios/View Elements/Match/MatchTableViewCell.swift
I think this will work for now - closes #654
> Fix Match Summary background view inconsistent with cell highlight background color

- Frameworks/TBAData/Sources/Event/Event.swift
- Frameworks/TBAData/Tests/Event/EventTests.swift
- the-blue-alliance-ios/View Controllers/MyTBA/MyTBATableViewController.swift
- the-blue-alliance-ios/View Elements/Events/EventCellViewModel.swift
- the-blue-alliance-ios/View Elements/Events/EventTableViewCell.swift
- the-blue-alliance-ios/View Elements/Teams/TeamCellViewModel.swift
- the-blue-alliance-ios/View Elements/Teams/TeamTableViewCell.swift
This change looks MUCH better when showing events in the myTBA view where we're not filtering on year/week/type. Fixes #455
> Show full name for myTBA Event cells

- the-blue-alliance-ios/View Elements/Match/Breakdown/MatchBreakdownConfigurator2019.swift
- the-blue-alliance-ios/View Elements/Match/Breakdown/MatchBreakdownView.swift
Slightly better - the spacing is still weird, but it's good enough. Closes #842
> Fix 2019 total cargo/hatch image size

- the-blue-alliance-ios/View Controllers/Events/Event/EventInfoViewController.swift
Currently we're inserting two `.webcast` rows, which isn't unique in our diffable data source, and we crash. This adds the `Webcast` as an associated value, which as long as it's a different object, won't crash when an Event has multiple webcasts
> Fix crash when event has multiple webcasts

- the-blue-alliance-ios/View Elements/Events/Stats/EventStatsConfigurator2020.swift
`Energzied` -> `Energized`
the-blue-alliance/the-blue-alliance#2752
> Fix "energzied" typo

- Frameworks/TBAData/Sources/Event/Webcast.swift
The old YouTube link is right for channels, but wrong for streams 🤷‍♂
> Fix YouTube webcast watch link

- Frameworks/TBAData/Resources/TBA.xcdatamodeld/TBA.xcdatamodel/contents
- Frameworks/TBAData/Sources/Event/Webcast.swift
- Frameworks/TBAKit/Sources/TBAEvent.swift
- the-blue-alliance-ios/View Controllers/Events/Event/EventInfoViewController.swift
Showing both items with one screenshot - the streams link is now higher to promote watching streams from the app, and the webcasts are filtered if they have a date associated to only show webcasts on the same day
> Move webcast section above event info. Filter YouTube webcasts to be shown on the proper day

- tba-unit-tests/Services/HandoffServiceTests.swift
- tba-unit-tests/View Controllers/Districts/DistrictsContainerViewControllerTests.swift
- tba-unit-tests/View Controllers/Events/EventsContainerViewControllerTests.swift
- tba-unit-tests/View Controllers/Teams/TeamsContainerViewControllerTests.swift
- tba-unit-tests/View Controllers/myTBA/MyTBAViewControllerTests.swift
- the-blue-alliance-ios.xcodeproj/project.pbxproj
- the-blue-alliance-ios/App Delegate/AppDelegate.swift
- the-blue-alliance-ios/Extensions/UIDevice+TBA.swift
- the-blue-alliance-ios/Protocols/SearchContainer.swift
- the-blue-alliance-ios/Services/HandoffService.swift
- the-blue-alliance-ios/View Controllers/Districts/DistrictsContainerViewController.swift
- the-blue-alliance-ios/View Controllers/Events/EventsContainerViewController.swift
- the-blue-alliance-ios/View Controllers/MyTBA/MyTBAViewController.swift
- the-blue-alliance-ios/View Controllers/Root/PadRootViewController.swift
- the-blue-alliance-ios/View Controllers/Root/PhoneRootViewController.swift
- the-blue-alliance-ios/View Controllers/Root/RootController.swift
- the-blue-alliance-ios/View Controllers/Settings/SettingsViewController.swift
- the-blue-alliance-ios/View Controllers/Teams/TeamsContainerViewController.swift
This change removes the use of the `UISplitViewController` on iPhone and introduces a new navigation pattern of a root table view on iPad. This gives both iPhone and iPad two distinct navigation patterns that are proper for their platform, as opposed to shoehorning the iPhone navigation patterns in to iPad by using a hybrid tab view + split view approach.
Fixes #858, fixes #878
Only using the split view controller on iPad is probably the right approach from a hierarchical standpoint. There's some weirdness at the intersection of the split view controller + iPhone (such as #858). This also allows us to create a more iPad specific navigation flow, like removing the tabs on iPad but keeping them on iPhone.
Manually tested
> Only use split view controller on iPad

- the-blue-alliance-ios/View Controllers/Teams/Team/Team@Event/TeamSummaryViewController.swift
Another very cool undocumented API change in iOS 14 - the [`NSDiffableDataSourceSnapshot.itemIdentifiersInSection` method](https://developer.apple.com/documentation/uikit/nsdiffabledatasourcesnapshot/3375775-itemidentifiers) no longer returns an empty array if the section doesn't exist in the snapshot, it throws an error. This PR adds a check in the Team@Event view before attempting to re-use/update the existing Event Info section Status row.
Fixes #892
> Fix updating Team@Event view Event Info/Status sections crashing when Event Info section does not exist yet

- Frameworks/TBAData/Sources/Event/Event.swift
- Frameworks/TBAData/Tests/Event/EventTests.swift
- the-blue-alliance-ios/View Controllers/Districts/District/DistrictViewController.swift
- the-blue-alliance-ios/View Controllers/Events/EventsContainerViewController.swift
- the-blue-alliance-ios/View Controllers/Events/EventsViewController.swift
- the-blue-alliance-ios/View Controllers/Events/WeekEventsViewController.swift
- the-blue-alliance-ios/View Controllers/Events/YearSelectViewController.swift
Right now, 2021 events have a new type (`remote`) and are crashing in the app. This code allows for more gracefully handling unknown events by grouping all events without an event type together in to an "Unknown" section, so they're still displayed and things don't crash
> Remove force unwraps around eventType to handle unknown events

- the-blue-alliance-ios.xcodeproj/project.pbxproj
- the-blue-alliance-ios.xcodeproj/xcshareddata/xcschemes/TBA Spotlight Index Extension.xcscheme
- the-blue-alliance-ios/ViewControllers/Match/MatchBreakdownViewController.swift
- the-blue-alliance-ios/ViewElements/Match/Breakdown/MatchBreakdownConfigurator2024.swift
Added Match Breakdown for the 2024 game, Crescendo
Based layout on the site version of the Match Breakdown 
Based functionality on previous year's standards
There is no breakdown for 2024 yet, so I wanted to get that going before the season is over.
Will probably work on 2023 next since it's also missing :) 
Since this was only a change on the match breakdown page, I tested this against the full site on many different matches to make sure the information was correct.
I also added a couple more rows of data that aren't on the site (and let @dracco1993 know about these) that provide more data to uses about the extra RPs:
- How many notes were scored out of the total needed for a Melody RP
- How many Stage points an alliances scored for the match
> Added Match Breakdown for the 2024 game, Crescendo

- the-blue-alliance-ios/ViewControllers/Events/Event/EventInfoViewController.swift
- the-blue-alliance-ios/ViewControllers/Teams/Team/TeamInfoViewController.swift
- the-blue-alliance-ios/ViewElements/Info/InfoCellViewModel.swift
display team rookie year, event week number, remove # to team and event information
consistent with website version
local
> Team and Event Info
